package ast.interfaces;

import ast.Base;
import ast.Bexp;
import ast.Cexp;
import ast.Cont;
import ast.Dir;
import ast.Dirs;
import ast.Gather;
import ast.Query;
import ast.Rand;
import ast.astBase.ABase;
import ast.astBase.RBase;
import ast.astBexp.AndBExp;
import ast.astBexp.CExpBExp;
import ast.astBexp.NotBExp;
import ast.astBexp.OrBExp;
import ast.astBexp.SBExp;
import ast.astCexp.EQCExp;
import ast.astCexp.GCExp;
import ast.astCexp.GEQCExp;
import ast.astCexp.LCExp;
import ast.astCexp.LEQCExp;
import ast.astCont.DCont;
import ast.astCont.ECont;
import ast.astCont.FCont;
import ast.astDirs.FDirs;
import ast.astDirs.RDirs;
import ast.astGather.FGather;
import ast.astGather.RGather;
import ast.astQuery.BQuery;
import ast.astQuery.GQuery;
import ast.astRand.CRand;
import ast.astRand.SRand;
import fr.sorbonne_u.cps.sensor_network.requests.interfaces.ExecutionStateI;

public interface IASTvisitor<Result, Data, Anomaly extends Throwable> {
	Result visit(Query<?> ast, Data data) throws Anomaly;
	Result visit(BQuery ast, Data data) throws Anomaly;
	Result visit(GQuery ast, Data data) throws Anomaly;
    Result visit(Base ast, Data data) throws Anomaly;
    Result visit(ABase ast, Data data) throws Anomaly;
    Result visit(RBase ast, Data data) throws Anomaly;
    Result visit(Bexp ast, Data data) throws Anomaly;
    Result visit(AndBExp ast, Data data) throws Anomaly;
    Result visit(CExpBExp ast, Data data) throws Anomaly;
    Result visit(NotBExp ast, Data data) throws Anomaly;
    Result visit(OrBExp ast, Data data) throws Anomaly;
    Result visit(SBExp ast, Data data) throws Anomaly;
    Result visit(Cexp ast, Data data) throws Anomaly;
    Result visit(EQCExp ast, Data data) throws Anomaly;
    Result visit(GCExp ast, Data data) throws Anomaly;
    Result visit(GEQCExp ast, Data data) throws Anomaly;
    Result visit(LCExp ast, Data data) throws Anomaly;
    Result visit(LEQCExp ast, Data data) throws Anomaly;
    Result visit(Cont ast, Data data) throws Anomaly;
    Result visit(DCont ast, Data data) throws Anomaly;
    Result visit(ECont ast, Data data) throws Anomaly;
    Result visit(FCont ast, Data data) throws Anomaly;
    Result visit(Dir ast, Data data) throws Anomaly;
    Result visit(Dirs ast, Data data) throws Anomaly;
    Result visit(FDirs ast, Data data) throws Anomaly;
    Result visit(RDirs ast, Data data) throws Anomaly;
    Result visit(Gather ast, Data data) throws Anomaly;
    Result visit(FGather ast, Data data) throws Anomaly;
    Result visit(RGather ast, Data data) throws Anomaly;
    Result visit(Rand ast, Data data) throws Anomaly;
    Result visit(CRand ast, Data data) throws Anomaly;
    Result visit(SRand ast, Data data) throws Anomaly;


}
